### ISSUE TITLE
修改pythonpath后的config.ini的读写问题

### ISSUE THREAD

**Issue by HansenBurger** [HansenBurger/RespVariability#4]
# config.ini的读写问题

## 问题描述

使用了sys.path导入自定义包后，InIReaWri中的ConfigR无法正常运行，返回的结果都是config path error，但应该和该模块内定义的config_path无关，因为RSBI_1的测试中可以运行，TestCode/test.py中同样的代码段就不行。

**Comment by AbyssLink** [comment]
Python 在 b/b.py 中 import a/a.py，可能类似将 a/a.py 的代码插入到 b/b.py 中
原本相对于 a/a.py 的文件路径，解释时会被作为相对 b/b.py，导致文件无法找到

参考：https://realpython.com/python-import/

**Comment by HansenBurger** [comment]
修改InIReaWri中的config_path为绝对路径后即可解决。原因：导入模块后，模块的其他内容并不会绑定到当前namespace。
